package vista;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.SwingConstants;
import javax.swing.border.MatteBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juan
 */
public class VAdminEscuela extends javax.swing.JPanel {

    /**
     * Creates new form VistaEscuela1
     */
    public VAdminEscuela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabla = new JScrollPane();
        tablas = new JTable();
        jLabel3 = new JLabel();
        jSeparator2 = new JSeparator();
        btnTablaRecaudo = new JButton();
        btnTablaPersonal = new JButton();
        btnTablaCambio = new JButton();
        btnAnterior = new JLabel();
        btnSiguiente = new JLabel();
        btnPrimero = new JLabel();
        btnUltimo = new JLabel();
        btnEntregaRecaudos = new JButton();
        btnAsignarPersonal = new JButton();
        btnReporteRecaudo = new JButton();
        btnCambioEscuela = new JButton();
        btnReportePersonal = new JButton();
        btnReporteCambio = new JButton();

        FormListener formListener = new FormListener();

        setBackground(new Color(255, 255, 255));

        tabla.setName("tabla"); // NOI18N

        tablas.setModel(new DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablas.setName("tablas"); // NOI18N
        tabla.setViewportView(tablas);

        jLabel3.setFont(new Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel3.setText("Aministrar Escuelas");
        jLabel3.setName("jLabel3"); // NOI18N

        jSeparator2.setName("jSeparator2"); // NOI18N

        btnTablaRecaudo.setBackground(new Color(255, 153, 51));
        btnTablaRecaudo.setForeground(new Color(255, 255, 255));
        btnTablaRecaudo.setText("Recaudos Entregados");
        btnTablaRecaudo.setName("btnTablaRecaudo"); // NOI18N
        btnTablaRecaudo.addActionListener(formListener);

        btnTablaPersonal.setBackground(new Color(255, 153, 51));
        btnTablaPersonal.setForeground(new Color(255, 255, 255));
        btnTablaPersonal.setText("Personal Asignado");
        btnTablaPersonal.setName("btnTablaPersonal"); // NOI18N

        btnTablaCambio.setBackground(new Color(255, 153, 51));
        btnTablaCambio.setForeground(new Color(255, 255, 255));
        btnTablaCambio.setText("Cambio de Escuelas");
        btnTablaCambio.setName("btnTablaCambio"); // NOI18N

        btnAnterior.setForeground(new Color(0, 0, 0));
        btnAnterior.setText("Anterior");
        btnAnterior.setName("btnAnterior"); // NOI18N

        btnSiguiente.setForeground(new Color(0, 0, 0));
        btnSiguiente.setText("Siguiente");
        btnSiguiente.setName("btnSiguiente"); // NOI18N

        btnPrimero.setForeground(new Color(0, 0, 0));
        btnPrimero.setText("Primero");
        btnPrimero.setName("btnPrimero"); // NOI18N

        btnUltimo.setForeground(new Color(0, 0, 0));
        btnUltimo.setText("Ultimo");
        btnUltimo.setName("btnUltimo"); // NOI18N

        btnEntregaRecaudos.setBackground(new Color(255, 0, 51));
        btnEntregaRecaudos.setForeground(new Color(255, 255, 255));
        btnEntregaRecaudos.setText("Entrega de Recaudos");
        btnEntregaRecaudos.setName("btnEntregaRecaudos"); // NOI18N

        btnAsignarPersonal.setBackground(new Color(255, 0, 51));
        btnAsignarPersonal.setForeground(new Color(255, 255, 255));
        btnAsignarPersonal.setText("Asignar Personal");
        btnAsignarPersonal.setName("btnAsignarPersonal"); // NOI18N

        btnReporteRecaudo.setBackground(new Color(0, 102, 255));
        btnReporteRecaudo.setForeground(new Color(255, 255, 255));
        btnReporteRecaudo.setText("Repote de Recaudos");
        btnReporteRecaudo.setName("btnReporteRecaudo"); // NOI18N
        btnReporteRecaudo.addActionListener(formListener);

        btnCambioEscuela.setBackground(new Color(255, 0, 51));
        btnCambioEscuela.setForeground(new Color(255, 255, 255));
        btnCambioEscuela.setText("Cambio de Escuela");
        btnCambioEscuela.setName("btnCambioEscuela"); // NOI18N

        btnReportePersonal.setBackground(new Color(0, 102, 255));
        btnReportePersonal.setForeground(new Color(255, 255, 255));
        btnReportePersonal.setText("Reporte de Personal");
        btnReportePersonal.setToolTipText("");
        btnReportePersonal.setName("btnReportePersonal"); // NOI18N

        btnReporteCambio.setBackground(new Color(0, 102, 255));
        btnReporteCambio.setForeground(new Color(255, 255, 255));
        btnReporteCambio.setText("Reporte de Cambio de Escuela");
        btnReporteCambio.setName("btnReporteCambio"); // NOI18N

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jLabel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jSeparator2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addComponent(btnReporteCambio, GroupLayout.PREFERRED_SIZE, 190, GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnReportePersonal, GroupLayout.PREFERRED_SIZE, 190, GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnReporteRecaudo, GroupLayout.PREFERRED_SIZE, 190, GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnCambioEscuela, GroupLayout.PREFERRED_SIZE, 190, GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAsignarPersonal, GroupLayout.PREFERRED_SIZE, 190, GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnEntregaRecaudos, GroupLayout.PREFERRED_SIZE, 190, GroupLayout.PREFERRED_SIZE))
                            .addComponent(tabla, GroupLayout.PREFERRED_SIZE, 597, GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 28, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnTablaRecaudo, GroupLayout.PREFERRED_SIZE, 145, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTablaPersonal, GroupLayout.PREFERRED_SIZE, 145, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTablaCambio, GroupLayout.PREFERRED_SIZE, 145, GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
            .addGroup(layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(btnPrimero)
                .addGap(18, 18, 18)
                .addComponent(btnAnterior)
                .addGap(18, 18, 18)
                .addComponent(btnSiguiente)
                .addGap(18, 18, 18)
                .addComponent(btnUltimo)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEntregaRecaudos)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAsignarPersonal)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCambioEscuela)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReporteRecaudo)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReportePersonal)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReporteCambio)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTablaRecaudo)
                    .addComponent(btnTablaPersonal)
                    .addComponent(btnTablaCambio))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabla, GroupLayout.PREFERRED_SIZE, 269, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnterior)
                    .addComponent(btnSiguiente)
                    .addComponent(btnPrimero)
                    .addComponent(btnUltimo))
                .addGap(19, 19, 19))
        );
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements ActionListener {
        FormListener() {}
        public void actionPerformed(ActionEvent evt) {
            if (evt.getSource() == btnTablaRecaudo) {
                VAdminEscuela.this.btnTablaRecaudoActionPerformed(evt);
            }
            else if (evt.getSource() == btnReporteRecaudo) {
                VAdminEscuela.this.btnReporteRecaudoActionPerformed(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void btnTablaRecaudoActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnTablaRecaudoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTablaRecaudoActionPerformed

    private void btnReporteRecaudoActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnReporteRecaudoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReporteRecaudoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public JLabel btnAnterior;
    public JButton btnAsignarPersonal;
    public JButton btnCambioEscuela;
    public JButton btnEntregaRecaudos;
    public JLabel btnPrimero;
    public JButton btnReporteCambio;
    public JButton btnReportePersonal;
    public JButton btnReporteRecaudo;
    public JLabel btnSiguiente;
    public JButton btnTablaCambio;
    public JButton btnTablaPersonal;
    public JButton btnTablaRecaudo;
    public JLabel btnUltimo;
    public JLabel jLabel3;
    public JSeparator jSeparator2;
    public JScrollPane tabla;
    public JTable tablas;
    // End of variables declaration//GEN-END:variables

    public JLabel getBtnAnterior() {
        return btnAnterior;
    }

    public JButton getBtnAsignarPersonal() {
        return btnAsignarPersonal;
    }

    public JButton getBtnCambioEscuela() {
        return btnCambioEscuela;
    }

    public JButton getBtnEntregaRecaudos() {
        return btnEntregaRecaudos;
    }

    public JLabel getBtnPrimero() {
        return btnPrimero;
    }

    public JButton getBtnReporteCambio() {
        return btnReporteCambio;
    }

    public JButton getBtnReportePersonal() {
        return btnReportePersonal;
    }

    public JButton getBtnReporteRecaudo() {
        return btnReporteRecaudo;
    }

    public JLabel getBtnSiguiente() {
        return btnSiguiente;
    }

    public JButton getBtnTablaCambio() {
        return btnTablaCambio;
    }

    public JButton getBtnTablaPersonal() {
        return btnTablaPersonal;
    }

    public JButton getBtnTablaRecaudo() {
        return btnTablaRecaudo;
    }

    public JLabel getBtnUltimo() {
        return btnUltimo;
    }

    public JTable getTablas() {
        return tablas;
    }
    
    

}