package vista;

import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.SwingConstants;
import javax.swing.border.MatteBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Diego
 */
public class VEstudiante extends javax.swing.JPanel {

    /**
     * Creates new form VistaEstudiante1
     */
    public VEstudiante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpGenero = new ButtonGroup();
        jLabel3 = new JLabel();
        jSeparator1 = new JSeparator();
        jScrollPane2 = new JScrollPane();
        jPanel5 = new JPanel();
        jLabel2 = new JLabel();
        jLabel4 = new JLabel();
        jLabel5 = new JLabel();
        jLabel6 = new JLabel();
        cbxCedula = new JComboBox<>();
        txtCedula = new JTextField();
        txtPNombre = new JTextField();
        txtPApellido = new JTextField();
        jLabel8 = new JLabel();
        jScrollPane3 = new JScrollPane();
        txtDireccion = new JTextArea();
        jLabel9 = new JLabel();
        jLabel10 = new JLabel();
        txtEdad = new JTextField();
        jLabel1 = new JLabel();
        txtSNombre = new JTextField();
        jLabel7 = new JLabel();
        txtSApellido = new JTextField();
        btnNuevo = new JButton();
        btnAgregar = new JButton();
        btnModificar = new JButton();
        btnEliminar = new JButton();
        radBtnMasculino = new JRadioButton();
        radBtnFemenino = new JRadioButton();
        dateChooserFNacimiento = new JDateChooser();
        jLabel12 = new JLabel();
        cbxEscuela = new JComboBox<>();
        jScrollPane1 = new JScrollPane();
        tabla = new JTable();

        FormListener formListener = new FormListener();

        setBackground(new Color(255, 255, 255));

        jLabel3.setFont(new Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel3.setText("Estudiante");
        jLabel3.setName("jLabel3"); // NOI18N

        jSeparator1.setName("jSeparator1"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jPanel5.setBackground(new Color(255, 255, 255));
        jPanel5.setFont(new Font("Corbel", 0, 12)); // NOI18N
        jPanel5.setName("jPanel5"); // NOI18N

        jLabel2.setFont(new Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Primer Nombre:");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel4.setFont(new Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Cédula:");
        jLabel4.setHorizontalTextPosition(SwingConstants.CENTER);
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setFont(new Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Primer Apellido:");
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setFont(new Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Género:");
        jLabel6.setName("jLabel6"); // NOI18N

        cbxCedula.setFont(new Font("Tahoma", 0, 12)); // NOI18N
        cbxCedula.setModel(new DefaultComboBoxModel<>(new String[] { "V", "E" }));
        cbxCedula.setName("cbxCedula"); // NOI18N
        cbxCedula.addActionListener(formListener);

        txtCedula.setName("txtCedula"); // NOI18N
        txtCedula.addActionListener(formListener);

        txtPNombre.setName("txtPNombre"); // NOI18N
        txtPNombre.addActionListener(formListener);

        txtPApellido.setName("txtPApellido"); // NOI18N

        jLabel8.setFont(new Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Dirección:");
        jLabel8.setName("jLabel8"); // NOI18N

        jScrollPane3.setFont(new Font("Corbel", 0, 12)); // NOI18N
        jScrollPane3.setName("jScrollPane3"); // NOI18N
        jScrollPane3.setPreferredSize(new Dimension(100, 50));
        jScrollPane3.setRequestFocusEnabled(false);

        txtDireccion.setColumns(20);
        txtDireccion.setLineWrap(true);
        txtDireccion.setRows(3);
        txtDireccion.setName("txtDireccion"); // NOI18N
        jScrollPane3.setViewportView(txtDireccion);

        jLabel9.setFont(new Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Fecha de Nacimiento:");
        jLabel9.setName("jLabel9"); // NOI18N

        jLabel10.setFont(new Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Edad:");
        jLabel10.setName("jLabel10"); // NOI18N

        txtEdad.setName("txtEdad"); // NOI18N
        txtEdad.setPreferredSize(new Dimension(18, 23));
        txtEdad.addActionListener(formListener);

        jLabel1.setFont(new Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Segundo Nombre:");
        jLabel1.setName("jLabel1"); // NOI18N

        txtSNombre.setName("txtSNombre"); // NOI18N

        jLabel7.setFont(new Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Segundo Apellido:");
        jLabel7.setName("jLabel7"); // NOI18N

        txtSApellido.setName("txtSApellido"); // NOI18N

        btnNuevo.setBackground(new Color(238, 24, 24));
        btnNuevo.setFont(new Font("Tahoma", 0, 12)); // NOI18N
        btnNuevo.setForeground(new Color(255, 255, 255));
        btnNuevo.setText("Nuevo");
        btnNuevo.setBorder(new MatteBorder(null));
        btnNuevo.setBorderPainted(false);
        btnNuevo.setName("btnNuevo"); // NOI18N

        btnAgregar.setBackground(new Color(238, 24, 24));
        btnAgregar.setFont(new Font("Tahoma", 0, 12)); // NOI18N
        btnAgregar.setForeground(new Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.setBorder(new MatteBorder(null));
        btnAgregar.setBorderPainted(false);
        btnAgregar.setName("btnAgregar"); // NOI18N

        btnModificar.setBackground(new Color(238, 24, 24));
        btnModificar.setFont(new Font("Tahoma", 0, 12)); // NOI18N
        btnModificar.setForeground(new Color(255, 255, 255));
        btnModificar.setText("Modificar");
        btnModificar.setBorder(new MatteBorder(null));
        btnModificar.setBorderPainted(false);
        btnModificar.setName("btnModificar"); // NOI18N

        btnEliminar.setBackground(new Color(238, 24, 24));
        btnEliminar.setFont(new Font("Tahoma", 0, 12)); // NOI18N
        btnEliminar.setForeground(new Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(new MatteBorder(null));
        btnEliminar.setBorderPainted(false);
        btnEliminar.setName("btnEliminar"); // NOI18N

        radBtnMasculino.setBackground(new Color(255, 255, 255));
        btnGrpGenero.add(radBtnMasculino);
        radBtnMasculino.setText("Masculino");
        radBtnMasculino.setName("radBtnMasculino"); // NOI18N

        radBtnFemenino.setBackground(new Color(255, 255, 255));
        btnGrpGenero.add(radBtnFemenino);
        radBtnFemenino.setText("Femenino");
        radBtnFemenino.setName("radBtnFemenino"); // NOI18N

        dateChooserFNacimiento.setName("dateChooserFNacimiento"); // NOI18N

        jLabel12.setFont(new Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Escuela:");
        jLabel12.setName("jLabel12"); // NOI18N

        cbxEscuela.setName("cbxEscuela"); // NOI18N

        GroupLayout jPanel5Layout = new GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8)
                    .addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(cbxCedula, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCedula, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNuevo, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(txtEdad, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSNombre, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSApellido, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPApellido, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPNombre, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregar, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModificar, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(cbxEscuela, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(radBtnMasculino)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radBtnFemenino))
                            .addComponent(dateChooserFNacimiento, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cbxCedula, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCedula, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPNombre, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtSNombre, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtPApellido, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtSApellido, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(radBtnMasculino)
                            .addComponent(radBtnFemenino))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(dateChooserFNacimiento, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtEdad, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, 83, GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnNuevo, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAgregar, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModificar, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cbxEscuela, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jScrollPane2.setViewportView(jPanel5);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tabla.setModel(new DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabla.setName("tabla"); // NOI18N
        jScrollPane1.setViewportView(tabla);

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addComponent(jLabel3, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 251, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addContainerGap())
        );
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements ActionListener {
        FormListener() {}
        public void actionPerformed(ActionEvent evt) {
            if (evt.getSource() == cbxCedula) {
                VEstudiante.this.cbxCedulaActionPerformed(evt);
            }
            else if (evt.getSource() == txtCedula) {
                VEstudiante.this.txtCedulaActionPerformed(evt);
            }
            else if (evt.getSource() == txtPNombre) {
                VEstudiante.this.txtPNombreActionPerformed(evt);
            }
            else if (evt.getSource() == txtEdad) {
                VEstudiante.this.txtEdadActionPerformed(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void cbxCedulaActionPerformed(ActionEvent evt) {//GEN-FIRST:event_cbxCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCedulaActionPerformed

    private void txtCedulaActionPerformed(ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void txtPNombreActionPerformed(ActionEvent evt) {//GEN-FIRST:event_txtPNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPNombreActionPerformed

    private void txtEdadActionPerformed(ActionEvent evt) {//GEN-FIRST:event_txtEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnAgregar;
    private JButton btnEliminar;
    private ButtonGroup btnGrpGenero;
    private JButton btnModificar;
    private JButton btnNuevo;
    private JComboBox<String> cbxCedula;
    private JComboBox<String> cbxEscuela;
    private JDateChooser dateChooserFNacimiento;
    private JLabel jLabel1;
    private JLabel jLabel10;
    private JLabel jLabel12;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JPanel jPanel5;
    private JScrollPane jScrollPane1;
    private JScrollPane jScrollPane2;
    private JScrollPane jScrollPane3;
    private JSeparator jSeparator1;
    private JRadioButton radBtnFemenino;
    private JRadioButton radBtnMasculino;
    private JTable tabla;
    private JTextField txtCedula;
    private JTextArea txtDireccion;
    private JTextField txtEdad;
    private JTextField txtPApellido;
    private JTextField txtPNombre;
    private JTextField txtSApellido;
    private JTextField txtSNombre;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnNuevo() {
        return btnNuevo;
    }

    public JTable getTabla() {
        return tabla;
    }

    public JButton getBtnAgregar() {
        return btnAgregar;
    }

    public JButton getBtnEliminar() {
        return btnEliminar;
    }

    public ButtonGroup getBtnGrpGenero() {
        return btnGrpGenero;
    }

    public JButton getBtnModificar() {
        return btnModificar;
    }

    public JComboBox<String> getCbxCedula() {
        return cbxCedula;
    }

    public JRadioButton getRadBtnFemenino() {
        return radBtnFemenino;
    }

    public JRadioButton getRadBtnMasculino() {
        return radBtnMasculino;
    }

    public JTextField getTxtCedula() {
        return txtCedula;
    }

    public JTextArea getTxtDireccion() {
        return txtDireccion;
    }

    public JTextField getTxtEdad() {
        return txtEdad;
    }

    public JTextField getTxtPApellido() {
        return txtPApellido;
    }

    public JTextField getTxtPNombre() {
        return txtPNombre;
    }

    public JTextField getTxtSApellido() {
        return txtSApellido;
    }

    public JTextField getTxtSNombre() {
        return txtSNombre;
    }

    public JDateChooser getDateChooserFNacimiento() {
        return dateChooserFNacimiento;
    }

    public JComboBox<String> getCbxEscuela() {
        return cbxEscuela;
    }
}
