/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JLabel;

/**
 *
 * @author Diego
 */
public class VInicio extends javax.swing.JPanel {

    /**
     * Creates new form VInicio
     */
    public VInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnPedagogico = new javax.swing.JLabel();
        btnSegEscuela = new javax.swing.JLabel();
        btnAdminPersonal = new javax.swing.JLabel();
        btnAsistencia = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CONSIE");

        btnPedagogico.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnPedagogico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPedagogico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_student_male_120px.png"))); // NOI18N
        btnPedagogico.setText("Nivel Pedagógico");
        btnPedagogico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPedagogico.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnSegEscuela.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnSegEscuela.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSegEscuela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_school_building_120px.png"))); // NOI18N
        btnSegEscuela.setText("Seguimiento de Escuelas");
        btnSegEscuela.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSegEscuela.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnAdminPersonal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAdminPersonal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAdminPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_school_director_120px.png"))); // NOI18N
        btnAdminPersonal.setText("Seguimiento de Personal");
        btnAdminPersonal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdminPersonal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnAsistencia.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAsistencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAsistencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_statistics_120px.png"))); // NOI18N
        btnAsistencia.setText("Asistencia y Estadística");
        btnAsistencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAsistencia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPedagogico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAdminPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSegEscuela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAsistencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPedagogico, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSegEscuela, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdminPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAdminPersonal;
    private javax.swing.JLabel btnAsistencia;
    private javax.swing.JLabel btnPedagogico;
    private javax.swing.JLabel btnSegEscuela;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

  public JLabel getBtnAdminPersonal() {
        return btnAdminPersonal;
    }
    
    public JLabel getBtnSegEscuela() {
        return btnSegEscuela;
    }
    
    public JLabel getBtnAsistencia() {
        return btnAsistencia;
    }
    
    public JLabel getBtnPedagogico() {
        return btnPedagogico;
    }
    
}