package vista;

import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Diego
 */
public class VSeguimientoPersonal extends javax.swing.JPanel {

    /**
     * Creates new form VSeguimientoPersonal
     */
    public VSeguimientoPersonal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnEntregaRecaudos = new javax.swing.JButton();
        btnAsignarPersonal = new javax.swing.JButton();
        btnCambioEscuela = new javax.swing.JButton();
        btnReporteRecaudo = new javax.swing.JButton();
        btnReportePersonal = new javax.swing.JButton();
        btnReporteCambio = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Seguimiento de personal");

        btnEntregaRecaudos.setBackground(new java.awt.Color(255, 0, 51));
        btnEntregaRecaudos.setForeground(new java.awt.Color(255, 255, 255));
        btnEntregaRecaudos.setText("Asistencia de personal");

        btnAsignarPersonal.setBackground(new java.awt.Color(255, 0, 51));
        btnAsignarPersonal.setForeground(new java.awt.Color(255, 255, 255));
        btnAsignarPersonal.setText("Permisos laborales");

        btnCambioEscuela.setBackground(new java.awt.Color(255, 0, 51));
        btnCambioEscuela.setForeground(new java.awt.Color(255, 255, 255));
        btnCambioEscuela.setText("Vacaciones");

        btnReporteRecaudo.setBackground(new java.awt.Color(0, 102, 255));
        btnReporteRecaudo.setForeground(new java.awt.Color(255, 255, 255));
        btnReporteRecaudo.setText("Reporte de asistencia");
        btnReporteRecaudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteRecaudoActionPerformed(evt);
            }
        });

        btnReportePersonal.setBackground(new java.awt.Color(0, 102, 255));
        btnReportePersonal.setForeground(new java.awt.Color(255, 255, 255));
        btnReportePersonal.setText("Reporte de permisos");
        btnReportePersonal.setToolTipText("");

        btnReporteCambio.setBackground(new java.awt.Color(0, 102, 255));
        btnReporteCambio.setForeground(new java.awt.Color(255, 255, 255));
        btnReporteCambio.setText("Reporte de Vacaciones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnReporteCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReportePersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReporteRecaudo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCambioEscuela, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAsignarPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEntregaRecaudos, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEntregaRecaudos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAsignarPersonal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCambioEscuela)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReporteRecaudo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReportePersonal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReporteCambio)
                .addContainerGap(340, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnReporteRecaudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteRecaudoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReporteRecaudoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignarPersonal;
    private javax.swing.JButton btnCambioEscuela;
    private javax.swing.JButton btnEntregaRecaudos;
    private javax.swing.JButton btnReporteCambio;
    private javax.swing.JButton btnReportePersonal;
    private javax.swing.JButton btnReporteRecaudo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
